import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from '@/components/NavBar';
import BreadcrumbBox from '@/components/BreadcrumbBox';
export const metadata: Metadata = {
    title: "My KungFu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className='flex flex-col min-h-screen'>
                <NavBar />
                <BreadcrumbBox />
                <div className="flex-grow bg-gray-100 relative">
                    {children}
                </div>
            </body>
        </html>
    );
}
