import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from '@/components/NavBar';
import { Footer } from '@/components/Footer';
export const metadata: Metadata = {
    title: "My KungFu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NavBar />
                <div className="bg-gray-100">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
